
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wted_db?serverTimezone=UTC
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource

#  mybatis:
#    mapper-locations: classpath*:mapper/*.xml
#    configuration:
#      map-underscore-to-camel-case: true


    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.blockbus.wted.core.user.entity
  #typeEnumsPackage: com.blockbus.wted.core.user.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置控制台打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



# 配置日志
logging:
  config: classpath:config/logback-spring.xml

# 自定义参数
log:
  path: /Users/shangqiankun/work/log


  #redis 配置
  redis:
    host: 192.168.56.101
    port: 6379
    password: 123456
    timeout: 30000
    jedis:
      pool:
        max-idle: 5
        max-active: 10
        max-wait: -1
        min-idle: 1
